# Generated by Django 5.2.3 on 2025-06-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facialrecognition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facial Recognition', 'verbose_name_plural': 'Facial Recognitions'},
        ),
        migrations.AddField(
            model_name='facialrecognition',
            name='comparison_result',
            field=models.CharField(choices=[('same', 'Same Person'), ('different', 'Different Person'), ('no_face', 'No Face Detected'), ('error', 'Error Occurred'), ('pending', 'Pending')], default='pending', help_text='Result of the facial recognition comparison', max_length=20),
        ),
        migrations.AddField(
            model_name='facialrecognition',
            name='result_details',
            field=models.TextField(blank=True, help_text='Additional details about the comparison result', null=True),
        ),
        migrations.AddField(
            model_name='facialrecognition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
